openapi: 3.0.1
info:
  version: 1.0.0
  title: Attestasjon API (sokos-oppdrag)
  description: API-tjeneste for å søke etter attestasjonsdata
  contact:
    name: Team Moby (Motta og Beregne Ytelser)
    email: okonomi@nav.no
    url: https://nav-it.slack.com/archives/CKZADNFBP

tags:
  - name: attestasjon
    description: Opplysninger om attesterte oppdrag

servers:
  - url: /api/v1/attestasjon

paths:
  /personsok:
    post:
      tags:
        - attestasjon
      summary: Søk med gjelderId
      description: Returnerer oppdrag tilknyttet person eller foretak basert på 9 eller 11 siffer gjelderId.
      operationId: hentOppdragForAttestering
      requestBody:
        description: gjelderId er et krav
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GjelderIdRequest'
        required: true
      responses:
        200:
          description: OK - Hvis oppdrag ikke finnes, returneres tom liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AttestasjonTreff'
        400:
          description: Ugyldig request, oppfyller ikke swagger-kontrakt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        401:
          description: Ingen tilgang
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      security:
        - Bearer: [ ]

  /oppdragslinjer/{oppdragsId}:
    get:
      tags:
        - attestasjon
      summary: Søk med oppdragsid
      description: Returnerer oppdragslinjene til valgte oppdrag.
      operationId: hentOppdragslinjerForAttestering
      parameters:
        - name: oppdragsId
          in: path
          description: Oppdragets id
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK - Hvis oppdraget ikke finnes, returneres tom liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Attestasjonsdetaljer'
        400:
          description: Ugyldig request, oppfyller ikke swagger-kontrakt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        401:
          description: Ingen tilgang
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      security:
        - Bearer: [ ]
components:
  schemas:
    GjelderIdRequest:
      type: object
      required:
        - gjelderId
      properties:
        gjelderId:
          type: string
          example: "9 eller 11 siffer"
          description: 9 eller 11 siffer

    AttestasjonTreff:
      type: object
      properties:
        navnFaggruppe:
          type: string
        navnFagomraade:
          type: string
        oppdragsId:
          type: integer
        fagsystemId:
          type: string

    Attestasjonsdetaljer:
      type: object
      required:
        - klasse
        - delytelsesId
        - sats
        - satstype
        - datoVedtakFom
        - attestert
        - navnFagomraade
        - fagsystemId
      properties:
        klasse:
          type: string
        delytelsesId:
          type: string
        sats:
          type: number
        satstype:
          type: string
        datoVedtakFom:
          type: string
        datoVedtakTom:
          type: string
        attestert:
          type: string
        attestant:
          type: string
        navnFagomraade:
          type: string
        fagsystemId:
          type: string
    ApiError:
      type: object
      required:
        - timestamp
        - status
        - error
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
          description: Tidspunkt feilen oppsto
        status:
          type: integer
          example: 4xx
          description: HTTP status kode
        error:
          type: string
          example: Bad Request
          description: En kort, lesbar oppsummering av problemet
        message:
          type: string
          example: Det skjedde en feil
          description: En lesbar forklaring som er spesifikk for denne forekomsten av problemet
        path:
          type: string
          example: /api/v1/integration/personsok
          description: Endepunktet hvor feilen oppstå

  securitySchemes:
    Bearer:
      type: apiKey
      description: |-
        OBO-token (JWT via OAuth2.0).<br> 
          Følgende format må brukes i input-feltet "Value" under: <strong>\"Bearer {token}\"</strong>.<br> 
          Eksempel på verdi i input-felt: <strong>Bearer eYdmifml0ejugm</strong>
      name: Authorization
      in: header


