openapi: 3.0.1
info:
  version: 1.0.0
  title: Attestasjon API (sokos-oppdrag)
  description: API-tjeneste for å søke etter attestasjonsdata
  contact:
    name: Team Moby (Motta og Beregne Ytelser)
    email: okonomi@nav.no
    url: https://nav-it.slack.com/archives/CKZADNFBP

tags:
  - name: Attestasjon
    description: Opplysninger om attesterte oppdrag

servers:
  - url: /api/v1/attestasjon

paths:

  /sok:
    post:
      tags:
        - attestasjon
      summary: Søk etter oppdrag
      description: Returnerer oppdrag som er aktuelle for attestasjon
      operationId: getOppdrag
      requestBody:
        description: gjelderId, faggruppe, fagområde, fagsystem-id,
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OppdragsRequest'
        required: true
      responses:
        200:
          description: OK - Hvis oppdrag ikke finnes, returneres tom liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Oppdrag'
        400:
          description: Ugyldig request, oppfyller ikke swagger-kontrakt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        401:
          description: Ingen tilgang
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      security:
        - Bearer: [ ]

  /fagomraader:
    get:
      tags:
        - attestasjon
      summary: Hent tilgjengelige fagområder
      description: Returnerer en liste av tilgjengelige fagområder. Fagområde kan brukes til å filtrere søket i endepunktet -> /sok
      operationId: getFagOmraade
      responses:
        200:
          description: OK - Hvis fagområder ikke finnes så returneres tom liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FagOmraade'
      security:
        - Bearer: [ ]


  /oppdragsdetaljer/{oppdragsId}:
    get:
      tags:
        - attestasjon
      summary: Søk med oppdragsid
      description: Returnerer oppdragslinjene til valgte oppdrag.
      operationId: getOppdragsDetaljer
      parameters:
        - name: oppdragsId
          in: path
          description: Oppdragets id
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK - Hvis oppdragene ikke finnes, returneres tom liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OppdragsDetaljer'
        400:
          description: Ugyldig request, oppfyller ikke swagger-kontrakt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        401:
          description: Ingen tilgang
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      security:
        - Bearer: [ ]

  /attestere:
    post:
      tags:
        - attestasjon
      summary: Attestere eller avattestere oppdrag
      description: Returnerer status på attestert oppdrag
      operationId: attestereOppdrag
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AttestasjonRequest'
        required: true
      responses:
        200:
          description: OK - Kvittering på attestert oppdrag
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostOSAttestasjonResponse200'
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      security:
        - Bearer: [ ]

components:
  schemas:
    OppdragsRequest:
      type: object
      properties:
        gjelderId:
          type: string
          example: "9 eller 11 siffer"
          description: 9 eller 11 siffer
          nullable: true
        fagSystemId:
          type: string
          example: "TU000123456789012"
          nullable: true
        kodeFagGruppe:
          type: string
          example: "PEN"
          nullable: true
        kodeFagOmraade:
          type: string
          example: "MBA"
          nullable: true
        attestert:
          type: boolean
          example: true
          nullable: true

    AttestasjonRequest:
      type: object
      properties:
        gjelderId:
          type: string
          example: "9 eller 11 siffer"
          description: 9 eller 11 siffer
        fagSystemId:
          type: string
          example: "TU000123456789012"
        kodeFagOmraade:
          type: string
          example: "MBA"
        oppdragsId:
            type: number
            example: 12345678
            description: 8 siffer
        linjer:
            type: array
            items:
              $ref: '#/components/schemas/AttestasjonLinje'

    PostOSAttestasjonResponse200:
      type: object
      properties:
        OSAttestasjonOperationResponse:
          type: object
          properties:
            Attestasjonskvittering:
              type: object
              properties:
                ResponsAttestasjon:
                  type: object
                  properties:
                    GjelderId:
                      type: string
                      maxLength: 11
                    OppdragsId:
                      type: integer
                      minimum: 0
                      maximum: 9999999999
                    AntLinjerMottatt:
                      type: integer
                      minimum: 0
                      maximum: 99999
                    Statuskode:
                      type: integer
                      minimum: 0
                      maximum: 99
                    Melding:
                      type: string
                      maxLength: 100
          required:
            - Attestasjonskvittering

    AttestasjonLinje:
      type: object
      properties:
        linjeId:
          type: number
          example: 1
          description: Nummer på linjen om skal oppdateres
        attestantIdent:
          type: string
          example: "Z999999"
          description: Ansatt nummer til attestant
        datoUgyldigFom:
          type: string
          example: "2021-01-01"
          description: Dato for ugyldig fra

    Oppdrag:
      type: object
      required:
        - fagSystemId
        - gjelderId
        - kostnadsSted
        - fagGruppe
        - kodeFagGruppe
        - fagOmraade
        - kodeFagOmraade
        - oppdragsId
      properties:
        ansvarsSted:
          type: string
        gjelderId:
          type: string
        kostnadsSted:
          type: string
        fagGruppe:
          type: string
        kodeFagGruppe:
          type: string
        fagOmraade:
          type: string
        kodeFagOmraade:
          type: string
        oppdragsId:
          type: integer
        fagSystemId:
          type: string

    FagOmraade:
      type: object
      required:
        - navn
        - kode
      properties:
        navn:
          type: string
        kode:
          type: string

    OppdragsDetaljer:
      type: object
      required:
        - antallAttestanter
        - datoVedtakFom
        - delytelsesId
        - fagSystemId
        - gjelderId
        - kodeKlasse
        - kodeFagOmraade
        - kostnadsStedForOppdrag
        - linjeId
        - fagGruppe
        - fagOmraade
        - oppdragsId
        - sats
        - satstype
      properties:
        ansvarsStedForOppdrag:
          type: string
        ansvarsStedForOppdragsLinje:
          type: string
        antallAttestanter:
          type: integer
        attestant:
          type: string
        datoUgyldigFom:
          type: string
        datoVedtakFom:
          type: string
        datoVedtakTom:
          type: string
        delytelsesId:
          type: string
        gjelderId:
          type: string
        fagSystemId:
          type: string
        kodeKlasse:
          type: string
        kodeFagOmraade:
            type: string
        kostnadsStedForOppdrag:
          type: string
        kostnadsStedForOppdragsLinje:
          type: string
        linjeId:
          type: string
        fagGruppe:
          type: string
        fagOmraade:
          type: string
        oppdragsId:
          type: string
        sats:
          type: number
        satstype:
          type: string
    ApiError:
      type: object
      required:
        - timestamp
        - status
        - error
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
          description: Tidspunkt feilen oppsto
        status:
          type: integer
          example: 4xx
          description: HTTP status kode
        error:
          type: string
          example: Bad Request
          description: En kort, lesbar oppsummering av problemet
        message:
          type: string
          example: Det skjedde en feil
          description: En lesbar forklaring som er spesifikk for denne forekomsten av problemet
        path:
          type: string
          example: /api/v1/attestasjon/sok
          description: Endepunktet hvor feilen oppstå

  securitySchemes:
    Bearer:
      type: apiKey
      description: |-
        OBO-token (JWT via OAuth2.0).<br> 
          Følgende format må brukes i input-feltet "Value" under: <strong>\"Bearer {token}\"</strong>.<br> 
          Eksempel på verdi i input-felt: <strong>Bearer eYdmifml0ejugm</strong>
      name: Authorization
      in: header


