openapi: 3.0.1
info:
  version: 1.0.0
  title: Attestasjon API (sokos-oppdrag)
  description: API-tjeneste for å søke etter attestasjonsdata
  contact:
    name: Team Moby (Motta og Beregne Ytelser)
    email: okonomi@nav.no
    url: https://nav-it.slack.com/archives/CKZADNFBP

tags:
  - name: Attestasjon
    description: Opplysninger om attesterte oppdrag

servers:
  - url: /api/v1/attestasjon

paths:

  /sok:
    post:
      tags:
        - attestasjon
      summary: Søk etter oppdrag
      description: Returnerer oppdrag som er aktuelle for attestasjon
      operationId: getOppdrag
      requestBody:
        description: gjelderId, faggruppe, fagområde, fagsystem-id,
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OppdragsRequest'
        required: true
      responses:
        200:
          description: OK - Hvis oppdrag ikke finnes, returneres tom liste
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedDTO'
        400:
          description: Ugyldig request, oppfyller ikke swagger-kontrakt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        401:
          description: Ingen tilgang
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      security:
        - Bearer: [ ]

  /fagomraader:
    get:
      tags:
        - attestasjon
      summary: Hent tilgjengelige fagområder
      description: Returnerer en liste av tilgjengelige fagområder. Fagområde kan brukes til å filtrere søket i endepunktet -> /sok
      operationId: getFagOmraade
      responses:
        200:
          description: OK - Hvis fagområder ikke finnes så returneres tom liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FagOmraade'
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      security:
        - Bearer: [ ]


  /{oppdragsId}/oppdragsdetaljer:
    get:
      tags:
        - attestasjon
      summary: Søk med oppdragsid
      description: Returnerer oppdragslinjene til valgte oppdrag.
      operationId: getOppdragsDetaljer
      parameters:
        - name: oppdragsId
          in: path
          description: Oppdragets id
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK - Hvis oppdragene ikke finnes, returneres tom liste
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OppdragsdetaljerDTO'
        400:
          description: Ugyldig request, oppfyller ikke swagger-kontrakt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      security:
        - Bearer: [ ]

  /attestere:
    post:
      tags:
        - attestasjon
      summary: Attestere eller avattestere oppdrag
      description: Returnerer status på attestert oppdrag
      operationId: attestereOppdrag
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AttestasjonRequest'
        required: true
      responses:
        200:
          description: OK - Kvittering på attestert oppdrag
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZOsResponse'
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      security:
        - Bearer: [ ]

components:
  schemas:
    OppdragsRequest:
      type: object
      properties:
        gjelderId:
          type: string
          example: "9 eller 11 siffer"
          description: 9 eller 11 siffer
          nullable: true
        fagSystemId:
          type: string
          example: "TU000123456789012"
          nullable: true
        kodeFagGruppe:
          type: string
          example: "PEN"
          nullable: true
        kodeFagOmraade:
          type: string
          example: "MBA"
          nullable: true
        attestert:
          type: boolean
          example: true
          nullable: true

    AttestasjonRequest:
      type: object
      properties:
        gjelderId:
          type: string
          example: "9 eller 11 siffer"
          description: 9 eller 11 siffer
        fagSystemId:
          type: string
          example: "TU000123456789012"
        kodeFagOmraade:
          type: string
          example: "MBA"
        oppdragsId:
          type: number
          example: 12345678
          description: 8 siffer
        linjer:
          type: array
          items:
            $ref: '#/components/schemas/AttestasjonLinje'

    PaginatedDTO:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/OppdragDTO"
        page:
          type: integer
          example: 0
        rows:
          type: integer
          example: 10
        total:
          type: integer
          example: 100

    ZOsResponse:
      type: object
      properties:
        message:
          type: string
          example: "Oppdatering vellykket. 2 linjer oppdatert."
          description: Melding om oppdatering er vellykket og antall linjer oppdatert

    Attestasjon:
      type: object
      properties:
        attestant:
          type: string
        datoUgyldigFom:
          type: string

    AttestasjonLinje:
      type: object
      properties:
        linjeId:
          type: number
          example: 1
          description: Nummer på linjen om skal oppdateres
        attestantIdent:
          type: string
          example: "Z999999"
          description: Ansatt nummer til attestant
        datoUgyldigFom:
          type: string
          example: "2021-01-01"
          description: Dato for ugyldig fra

    FagOmraade:
      type: object
      required:
        - navn
        - kode
      properties:
        navn:
          type: string
        kode:
          type: string

    OppdragDTO:
      type: object
      properties:
        ansvarsSted:
          type: string
        antallAttestanter:
          type: integer
        fagGruppe:
          type: string
        fagOmraade:
          type: string
        fagSystemId:
          type: string
        gjelderId:
          type: string
        kostnadsSted:
          type: string
        kodeFagGruppe:
          type: string
        kodeFagOmraade:
          type: string
        oppdragsId:
          type: integer
        erSkjermetForSaksbehandler:
          type: boolean
        hasWriteAccess:
          type: boolean

    OppdragsdetaljerDTO:
      type: object
      properties:
        linjer:
          type: array
          items:
            $ref: '#/components/schemas/OppdragslinjeDTO'
        saksbehandlerIdent:
          type: string

    OppdragslinjeDTO:
      type: object
      properties:
        oppdragsLinje:
          $ref: '#/components/schemas/Oppdragslinje'
        ansvarsStedForOppdragsLinje:
          type: string
          nullable: true
        kostnadsStedForOppdragsLinje:
          type: string
          nullable: true
        attestasjoner:
          type: array
          items:
            $ref: '#/components/schemas/Attestasjon'

    Oppdragslinje:
      type: object
      properties:
        attestert:
          type: boolean
        datoVedtakFom:
          type: string
        datoVedtakTom:
          type: string
          nullable: true
        delytelseId:
          type: string
        kodeKlasse:
          type: string
        linjeId:
          type: integer
        oppdragsId:
          type: integer
        sats:
          type: number
        typeSats:
          type: string
        grad:
            type: number
            nullable: true
        kid:
            type: string
            nullable: true
        kontonummer:
            type: string
            nullable: true
        utbetalesTil:
            type: string
            nullable: true
        skyldner:
            type: string
            nullable: true
        refusjonsid:
            type: string
            nullable: true


    ApiError:
      type: object
      required:
        - timestamp
        - status
        - error
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
          description: Tidspunkt feilen oppsto
        status:
          type: integer
          example: 4xx
          description: HTTP status kode
        error:
          type: string
          example: Bad Request
          description: En kort, lesbar oppsummering av problemet
        message:
          type: string
          example: Det skjedde en feil
          description: En lesbar forklaring som er spesifikk for denne forekomsten av problemet
        path:
          type: string
          example: /api/v1/attestasjon/sok
          description: Endepunktet hvor feilen oppstå

  securitySchemes:
    Bearer:
      type: apiKey
      description: |-
        OBO-token (JWT via OAuth2.0).<br> 
          Følgende format må brukes i input-feltet "Value" under: <strong>\"Bearer {token}\"</strong>.<br> 
          Eksempel på verdi i input-felt: <strong>Bearer eYdmifml0ejugm</strong>
      name: Authorization
      in: header


