openapi: 3.0.1
info:
  version: 1.0.0
  title: Faste data API (sokos-oppdrag)
  description: API-tjeneste for å hente faste data
  contact:
    name: Team Moby (Motta og Beregne Ytelser)
    email: okonomi@nav.no
    url: https://nav-it.slack.com/archives/CKZADNFBP

tags:
  - name: Faste data
    description: Oppslag om faste data

servers:
  - url: /api/v1/fastedata

paths:

  /fagomraader:
    get:
      tags:
        - fastedata
      summary: Hent tilgjengelige fagområder
      description: Returnerer en liste av tilgjengelige fagområder. Fagområde kan brukes til å filtrere søket i endepunktet -> /sok
      operationId: getFagomraader
      responses:
        200:
          description: OK - Hvis fagområder ikke finnes så returneres tom liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Fagomraade'
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      security:
        - Bearer: [ ]


  /{kodeFagomraade}/korrigeringsaarsaker:
    get:
      tags:
        - fastedata
      summary: Søk med fagområde kode
      description: Returnerer korrigeringsårsaker for fagområde.
      operationId: getKorrigeringsaarsaker
      parameters:
        - name: kodeFagomraade
          in: path
          description: Fagområdets kode
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK - Hvis fagområder ikke finnes så returneres tom liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/KorrigeringsaarsakDTO'
        400:
          description: Ugyldig request, oppfyller ikke swagger-kontrakt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      security:
        - Bearer: [ ]

  /{kodeFagomraade}/bilagstyper:
    get:
      tags:
        - fastedata
      summary: Søk med fagområde kode
      description: Returnerer bilagstyper for fagområde.
      operationId: getBilagstyper
      parameters:
        - name: kodeFagomraade
          in: path
          description: Fagområdets kode
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK - Hvis fagområder ikke finnes så returneres tom liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bilagstype'
        400:
          description: Ugyldig request, oppfyller ikke swagger-kontrakt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      security:
        - Bearer: [ ]

  /{kodeFagomraade}/klassekoder:
    get:
      tags:
        - fastedata
      summary: Søk med fagområde kode
      description: Returnerer klassekoder for fagområde.
      operationId: getKlassekoder
      parameters:
        - name: kodeFagomraade
          in: path
          description: Fagområdets kode
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK - Hvis fagområder ikke finnes så returneres tom liste
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Klassekode'
        400:
          description: Ugyldig request, oppfyller ikke swagger-kontrakt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
        500:
          description: Annen feil
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiError'
      security:
        - Bearer: [ ]

components:
  schemas:
    Fagomraade:
      type: object
      properties:
         antallAttestanter:
           type: number
         anviser:
           type: string
         bilagstypeFinnes:
           type: boolean
         klassekodeFinnes:
           type: boolean
         kodeFagomraade:
           type: string
         kodeFaggruppe:
           type: string
         korraarsakFinnes:
           type: boolean
         kodeMotregningsgruppe:
           type: string
         maksAktiveOppdrag:
           type: number
         navnFagomraade:
           type: string
         regelFinnes:
           type: boolean
         sjekkMotTps:
           type: string
         sjekkOffId:
           type: string
         tpsDistribusjon:
           type: string

    KorrigeringsaarsakDTO:
      type: object
      properties:
        navn:
          type: string
        kode:
          type: string
        medforerKorrigering:
          type: boolean

    Bilagstype:
        type: object
        properties:
          kodeFagomraade:
            type: string
          typeBilag:
            type: string
          datoFom:
            type: string
          datoTom:
            type: string
          autoFagsystemId:
            type: string

    Klassekode:
      type: object
      properties:
        kodeKlasse:
          type: string


    ApiError:
      type: object
      required:
        - timestamp
        - status
        - error
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
          description: Tidspunkt feilen oppsto
        status:
          type: integer
          example: 4xx
          description: HTTP status kode
        error:
          type: string
          example: Bad Request
          description: En kort, lesbar oppsummering av problemet
        message:
          type: string
          example: Det skjedde en feil
          description: En lesbar forklaring som er spesifikk for denne forekomsten av problemet
        path:
          type: string
          example: /api/v1/attestasjon/sok
          description: Endepunktet hvor feilen oppstå

  securitySchemes:
    Bearer:
      type: apiKey
      description: |-
        OBO-token (JWT via OAuth2.0).<br> 
          Følgende format må brukes i input-feltet "Value" under: <strong>\"Bearer {token}\"</strong>.<br> 
          Eksempel på verdi i input-felt: <strong>Bearer eYdmifml0ejugm</strong>
      name: Authorization
      in: header


