openapi: 3.0.3
info:
  title: Venteregister API
  version: 1.0.0
paths:
  /hentBeregninger:
    post:
      summary: Hent beregninger
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HentBeregningerRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HentBeregningerResponse'
components:
  schemas:
    HentBeregningerRequest:
      type: object
      properties:
        GjelderId:
          type: string
        UtbetalesTilId:
          type: string
        Faggruppe:
          type: string
        Fagomraade:
          type: string
        FagsystemId:
          type: string
        OppdragsId:
          type: integer
        EnhetBosted:
          type: string
        EnhetBehand:
          type: string
        DatoBeregnet:
          type: string
          format: date
        DatoPeriodeFom:
          type: string
          format: date
        DatoPeriodeTom:
          type: string
          format: date
        BrukerId:
          type: string
        SokBeregningsId:
          type: integer
        TypeBilag:
          type: string
        KodeStatusTab:
          type: array
          items:
            $ref: '#/components/schemas/KodeStatus'
    KodeStatus:
      type: object
      properties:
        KodeStatus:
          type: string
    Beregning:
      type: object
      properties:
        FaggruppeNavn:
          type: string
        DatoBeregnet:
          type: string
          format: date
        BeregningsId:
          type: integer
        TypeBilag:
          type: string
        GjelderId:
          type: string
        Sum:
          type: number
          format: double
        GjelderNavn:
          type: string
        EnhetBehandlet:
          type: string
        Faggruppe:
          type: string
    HentBeregningerResponse:
      type: object
      properties:
        Beregninger:
          type: array
          items:
            $ref: '#/components/schemas/Beregning'