apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: okonomi
  annotations:
    "nais.io/run-as-group": "0"
    "nais.io/read-only-file-system": "false"
  name: sokos-oppdrag-valkey
  namespace: okonomi
spec:
  image: {{image}}
  port: 6379
  replicas:
    max: 1
    min: 1
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi
  accessPolicy:
    inbound:
      rules:
        - application: sokos-oppdrag
  service:
    port: 6379
    protocol: redis
  envFrom:
    - secret: sokos-oppdrag-valkey-password