apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sokos-oppdrag
  namespace: okonomi
  labels:
    team: okonomi
spec:
  groups:
    - name: sokos-oppdrag-alerts
      rules:
        - alert: sokos-oppdrag er nede
          expr: kube_deployment_status_replicas_available{deployment="sokos-oppdrag"} == 0
          for: 5m
          annotations:
            action: "Sjekk hvorfor applikasjonen er nede"
            summary: "{{ $labels.deployment }} er nede i namespace {{ $labels.namespace }}"
          labels:
            namespace: okonomi
            severity: critical
            sokos_oppdrag_type: sokos-oppdrag
            alert_type: custom

        - alert: sokos-oppdrag har restartet flere ganger de siste 5 minuttene!
          expr: sum(increase(kube_pod_container_status_restarts_total{container=~"sokos-oppdrag"}[5m])) by (container) > 2
          for: 5m
          annotations:
            action: "Sjekk hvorfor applikasjonen ikke klarer å restarte"
            summary: "{{ $labels.container }} restarter mange ganger"
          labels:
            namespace: okonomi
            severity: critical
            sokos_oppdrag_type: sokos-oppdrag
            alert_type: custom

        - alert: Applikasjonen logger høy andel errors
          expr: |
            max_over_time((sum(loki:service:loglevel:count1m{service_name="sokos-oppdrag", detected_level="error"}) / sum(loki:service:loglevel:count1m{service_name="sokos-oppdrag"}))[15m:]) > 0.05
          for: 5m
          annotations:
            action: "<https://grafana.nav.cloud.nais.io/a/grafana-lokiexplore-app/explore/service_name/sokos-oppdrag/logs?patterns=%5B%5D&from=now-24h&to=now&var-filters=service_name%7C%3D%7Csokos-oppdrag&var-ds=dev-gcp-loki&var-levels=detected_level%7C%3D%7Cerror|Sjekk loggene>"
            summary: "`kubectl logs -l app=sokos-oppdrag -n okonomi` for logger"
          labels:
            namespace: okonomi
            severity: danger
            sokos_oppdrag_type: sokos-oppdrag
            alert_type: custom

        - alert: Applikasjonen logger høy andel warnings
          expr: |
            max_over_time((sum(loki:service:loglevel:count1m{service_name="sokos-oppdrag", detected_level="warn"}) / sum(loki:service:loglevel:count1m{service_name="sokos-oppdrag"}))[15m:]) > 0.05
          for: 5m
          annotations:
            action: "<https://grafana.nav.cloud.nais.io/a/grafana-lokiexplore-app/explore/service_name/sokos-oppdrag/logs?patterns=%5B%5D&from=now-24h&to=now&var-filters=service_name%7C%3D%7Csokos-oppdrag&var-ds=dev-gcp-loki&var-levels=detected_level%7C%3D%7Cwarn|Sjekk loggene>"
            summary: "`kubectl logs -l app=sokos-oppdrag -n okonomi` for logger"
          labels:
            namespace: okonomi
            severity: warning
            sokos_oppdrag_type: sokos-oppdrag
            alert_type: custom

        - alert: sokos-oppdrag har høy andel HTTP serverfeil (5xx responser)
          expr: floor(increase(ktor_http_server_requests_seconds_count{status=~"5.*", app="sokos-oppdrag"}[3m])) > 2
          for: 5m
          annotations:
            action: "`kubectl logs {{ $labels.pod }} -n {{ $labels.namespace }}`"
            summary: "Følgende request feilet: `Status {{ $labels.status }} - {{ $labels.method }} {{ $labels.route }}`.
                      Sjekk loggene for å se hvorfor dette feiler."
          labels:
            namespace: okonomi
            severity: critical
            sokos_oppdrag_type: sokos-oppdrag
            alert_type: custom

        - alert: sokos-oppdrag har høy andel HTTP klientfeil (4xx responser)
          expr: floor(increase(ktor_http_server_requests_seconds_count{status=~"4.*", status!~"404", app="sokos-oppdrag"}[3m])) > 2
          for: 2m
          annotations:
            action: "`kubectl logs {{ $labels.pod }} -n {{ $labels.namespace }}`"
            summary: "Følgende request feilet: `Status {{ $labels.status }} - {{ $labels.method }} {{ $labels.route }}`. 
                      Sjekk loggene for å se hvorfor dette feiler"
          labels:
            namespace: okonomi
            severity: critical
            sokos_oppdrag_type: sokos-oppdrag
            alert_type: custom

---

apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: sokos-oppdrag-slack
  namespace: okonomi
  labels:
    alertmanagerConfig: sokos-oppdrag-slack

spec:
  receivers:
    - name: sokos-oppdrag-receiver
      slackConfigs:
        - apiURL:
            key: apiUrl
            name: slack-webhook
          channel: '#team-mob-alerts-dev'
          iconEmoji: ':alert:'
          username: 'Alert dev-fss (sokos-oppdrag)'
          sendResolved: true
          title: |-
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
          text: >-
            {{ range .Alerts }}
            {{ if or .Annotations.summary .Annotations.message }}
            {{ or .Annotations.summary .Annotations.message }}
            {{ println " " }}
            {{- end }}
            {{- if .Annotations.action }}
            • *action*: {{ .Annotations.action }} {{ println " " }}
            {{- end }}
            {{ end }}
  route:
    groupBy:
      - alertname
    matchers:
      - name: "sokos_oppdrag_type"
        matchType: "="
        value: "sokos-oppdrag"
    groupInterval: 10s
    groupWait: 5s
    receiver: sokos-oppdrag-receiver
    repeatInterval:
