apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-oppdrag
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 2000m
      memory: 4096Mi
  ingresses:
    - https://sokos-oppdrag.intern.dev.nav.no
    - https://sokos-oppdrag.dev-fss-pub.nais.io
  prometheus:
    enabled: true
    path: /internal/metrics
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      claims:
        extra:
          - NAVident
        groups:
          - id: a0a00387-1830-47f6-af7e-3122c5940437 # 0000-GA-okonomi-fortrolig
          - id: 9d135c69-105c-4364-86f4-e22916758e93 # 0000-GA-okonomi-strengt_fortrolig
          - id: 1c7eec30-e0b3-4374-a175-13692bd299a3 # 0000-GA-okonomi-egne_ansatte
          - id: e1e9c6ba-114f-4b71-adf1-3db2f1608759 # 0000-GA-SOKOS-MF-Attestasjon-WRITE
  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: aura
          cluster: dev-gcp
        - application: sokos-utbetalingsportalen
          namespace: okonomi
          cluster: dev-gcp
  webproxy: true
  filesFrom:
    - secret: db2license
      mountPath: /var/run/secrets/db2license
  envFrom:
    - secret: oppdrag-credentials
  env:
    - name: USE_AUTHENTICATION
      value: "true"

    # OpenTelemetry
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "https://elastic-apm.adeo.no"
    - name: OTEL_METRICS_EXPORTER
      value: "otlp"
    - name: OTEL_LOGS_EXPORTER
      value: "none"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "service.name=sokos-oppdrag,service.version=sokos-oppdrag,deployment.environment=q"
    - name: OTEL_TRACES_EXPORTER
      value: "otlp"

    # Db2
    - name: DATABASE_HOST
      value: "155.55.1.82"
    - name: DATABASE_PORT
      value: "5025"
    - name: DATABASE_NAME
      value: "QDB2"
    - name: DATABASE_SCHEMA
      value: "OS231Q1"

    # Ereg
    - name: EREG_URL
      value: "https://ereg-services-q1.dev.intern.nav.no"

    # Nom
    - name: SKJERMING_URL
      value: http://skjermede-personer-pip.nom
    - name: SKJERMING_CLIENT_ID
      value: dev-gcp.nom.skjermede-personer-pip

    # Tp
    - name: TP_URL
      value: "https://tp-q1.dev.intern.nav.no"

    # Pdl
    - name: PDL_URL
      value: "https://pdl-api-q1.dev.intern.nav.no"
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api-q1/.default"

    # ZOS-Connect
    - name: ZOS_URL
      value: "https://155.55.1.82:9080/osattestasjonapi"