apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-oppdrag
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 75
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 2000m
      memory: 4096Mi
  ingresses:
    - https://sokos-oppdrag.intern.nav.no
    - https://sokos-oppdrag.prod-fss-pub.nais.io
  prometheus:
    enabled: true
    path: /internal/metrics
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      allowAllUsers: true
      claims:
        extra:
          - NAVident
        groups:
          - id: 420124f2-7456-4e3e-b035-7283bdabd51a # 0000-GA-okonomi-fortrolig
          - id: 22806019-fb74-41a5-a3cd-302624299935 # 0000-GA-okonomi-strengt_fortrolig
          - id: a3866f87-9b10-4b99-b4e9-a8c736d13b5b # 0000-GA-okonomi-egne_ansatte
          - id: ae748b4f-90d8-4635-afb6-60c24122a640 # 0000-GA-SOKOS-MF-Attestasjon-nasjonalt-READ Må oppdateres
          - id: c641ea06-9d84-4320-9f77-4df2ab8042c3 # 0000-GA-SOKOS-MF-Attestasjon-nasjonalt-WRITE Må oppdateres
          - id: 5785b537-7a62-4c81-bb09-27e42e8146cd # 0000-GA-SOKOS-MF-Attestasjon-NOP-READ Må oppdateres
          - id: c67369c0-9918-4f31-a952-121fc9d6d9e3 # 0000-GA-SOKOS-MF-Attestasjon-NOP-WRITE Må oppdateres
          - id: c8b782d6-12fd-4e1b-abed-04c6b09ad4e8 # 0000-GA-SOKOS-MF-Attestasjon-NOS-READ Må oppdateres
          - id: b02c819d-91e5-4cac-baf5-3d2411869adf # 0000-GA-SOKOS-MF-Attestasjon-NOS-WRITE Må oppdateres
  accessPolicy:
    inbound:
      rules:
        - application: sokos-utbetalingsportalen
          namespace: okonomi
          cluster: prod-gcp
  webproxy: true
  filesFrom:
    - secret: db2license
      mountPath: /var/run/secrets/db2license
  envFrom:
    - secret: oppdrag-q1-credentials # Må oppdateres
    - secret: sokos-oppdrag-redis-password
  env:
    - name: USE_AUTHENTICATION
      value: "true"

    # Redis
    - name: REDIS_HOST
      value: "sokos-oppdrag-redis.okonomi.svc.nais.local"
    - name: REDIS_PORT
      value: "6379"

    # Db2
    - name: DATABASE_HOST
      value: "155.55.1.82" # Må oppdateres
    - name: DATABASE_PORT
      value: "5025" # Må oppdateres
    - name: DATABASE_NAME
      value: "QDB2" # Må oppdateres
    - name: DATABASE_SCHEMA
      value: "OS231Q1" # Må oppdateres

    # Ereg
    - name: EREG_URL
      value: "https://ereg-services.intern.nav.no"

    # Nom
    - name: SKJERMING_URL
      value: "https://skjermede-personer-pip.nais.adeo.no" # Be om tilgang
    - name: SKJERMING_CLIENT_ID
      value: "api://prod-fss.nom.skjermede-personer-pip/.default"
    - name: GA_OKONOMI_EGNE_ANSATTE
      value: a3866f87-9b10-4b99-b4e9-a8c736d13b5b

    # Tp
    - name: TP_URL
      value: "https://tp.nais.adeo.no" # Sjekk om man må be om tilgang og at det er riktig ingress

    # PDL
    - name: PDL_URL
      value: "https://pdl-api.intern.nav.no/"
    - name: PDL_SCOPE
      value: "api://prod-fss.pdl.pdl-api/.default"
    - name: GA_OKONOMI_FORTROLIG
      value: 420124f2-7456-4e3e-b035-7283bdabd51a
    - name: GA_OKONOMI_STRENGT_FORTROLIG
      value: 22806019-fb74-41a5-a3cd-302624299935

    - name: GA_SOKOS_MF_ATTESTASJON_LANDSDEKKENDE_READ
      value: ae748b4f-90d8-4635-afb6-60c24122a640 # Må oppdateres
    - name: GA_SOKOS_MF_ATTESTASJON_LANDSDEKKENDE_WRITE
      value: c641ea06-9d84-4320-9f77-4df2ab8042c3 # Må oppdateres
    - name: GA_SOKOS_MF_ATTESTASJON_NOP_READ
      value: 5785b537-7a62-4c81-bb09-27e42e8146cd # Må oppdateres
    - name: GA_SOKOS_MF_ATTESTASJON_NOP_WRITE
      value: c67369c0-9918-4f31-a952-121fc9d6d9e3 # Må oppdateres
    - name: GA_SOKOS_MF_ATTESTASJON_NOS_READ
      value: c8b782d6-12fd-4e1b-abed-04c6b09ad4e8 # Må oppdateres
    - name: GA_SOKOS_MF_ATTESTASJON_NOS_WRITE
      value: b02c819d-91e5-4cac-baf5-3d2411869adf # Må oppdateres

    # ZOS-Connect
    - name: ZOS_URL
      value: "https://155.55.1.82:9080/osattestasjonapi" # Må oppdateres