apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-oppdrag
  namespace: okonomi
  labels:
    team: okonomi
spec:
  image: "{{{ image }}}"
  port: 8080
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  liveness:
    path: /internal/isAlive
    initialDelay: 5
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/isReady
    initialDelay: 5
    periodSeconds: 5
    timeout: 5
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 2000m
      memory: 4096Mi
  ingresses:
    - https://sokos-oppdrag.intern.dev.nav.no
    - https://sokos-oppdrag.dev-fss-pub.nais.io
  prometheus:
    enabled: true
    path: /internal/metrics
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
      claims:
        extra:
          - NAVident
        groups:
          - id: a0a00387-1830-47f6-af7e-3122c5940437 # 0000-GA-okonomi-fortrolig
          - id: 9d135c69-105c-4364-86f4-e22916758e93 # 0000-GA-okonomi-strengt_fortrolig
          - id: 1c7eec30-e0b3-4374-a175-13692bd299a3 # 0000-GA-okonomi-egne_ansatte
          - id: ae748b4f-90d8-4635-afb6-60c24122a640 # 0000-GA-SOKOS-MF-Attestasjon-Nasjonalt-READ
          - id: c641ea06-9d84-4320-9f77-4df2ab8042c3 # 0000-GA-SOKOS-MF-Attestasjon-Nasjonalt-WRITE
          - id: 5785b537-7a62-4c81-bb09-27e42e8146cd # 0000-GA-SOKOS-MF-Attestasjon-NOP-READ
          - id: c67369c0-9918-4f31-a952-121fc9d6d9e3 # 0000-GA-SOKOS-MF-Attestasjon-NOP-WRITE
          - id: c8b782d6-12fd-4e1b-abed-04c6b09ad4e8 # 0000-GA-SOKOS-MF-Attestasjon-NOS-READ
          - id: b02c819d-91e5-4cac-baf5-3d2411869adf # 0000-GA-SOKOS-MF-Attestasjon-NOS-WRITE
          - id: 992a8b83-5422-4cbf-af90-2d15fa0cfd88 # 0000-GA-SOKOS-MF-Oppdragsinfo-Nasjonalt-READ
          - id: a6fb82bd-cbca-4577-9156-fcabeb32404a # 0000-GA-SOKOS-MF-Oppdragsinfo-NØP-READ
          - id: fae560aa-11da-4fcc-b794-508908ab9ed4 # 0000-GA-SOKOS-MF-Oppdragsinfo-NØS-READ

  accessPolicy:
    inbound:
      rules:
        - application: azure-token-generator
          namespace: nais
          cluster: dev-gcp
        - application: sokos-utbetalingsportalen
          namespace: okonomi
          cluster: dev-gcp
  webproxy: true
  filesFrom:
    - secret: db2license
      mountPath: /var/run/secrets/db2license
  envFrom:
    - secret: oppdrag-q1-credentials
    - secret: sokos-oppdrag-mq-credentials
    - secret: sokos-oppdrag-valkey-password
  env:
    - name: USE_AUTHENTICATION
      value: "true"

    # Redis
    - name: VALKEY_HOST
      value: "sokos-oppdrag-valkey.okonomi.svc.nais.local"
    - name: VALKEY_PORT
      value: "6379"

    # Db2
    - name: DATABASE_HOST
      value: "155.55.1.82"
    - name: DATABASE_PORT
      value: "5025"
    - name: DATABASE_NAME
      value: "QDB2"
    - name: DATABASE_SCHEMA
      value: "OS231Q1"

    # Ereg
    - name: EREG_URL
      value: "https://ereg-services-q1.dev.intern.nav.no"

    # Nom
    - name: SKJERMING_URL
      value: "https://skjermede-personer-pip.intern.dev.nav.no"
    - name: SKJERMING_CLIENT_ID
      value: "api://dev-gcp.nom.skjermede-personer-pip/.default"
    - name: GA_OKONOMI_EGNE_ANSATTE
      value: 1c7eec30-e0b3-4374-a175-13692bd299a3

    # MQ
    - name: MQ_HOSTNAME
      value: mqls02.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_QUEUE_MANAGER_NAME
      value: MQLS02
    - name: MQ_CHANNEL_NAME
      value: Q1_SOKOS_OPPDRAG
    - name: MQ_TSS_SAMHANDLER_SERVICE_QUEUE
      value: QA.Q1_415.AS10_SAMHANDLER_SERVICE

    # Pdl
    - name: PDL_URL
      value: "https://pdl-api-q1.dev.intern.nav.no"
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api-q1/.default"
    - name: GA_OKONOMI_FORTROLIG
      value: a0a00387-1830-47f6-af7e-3122c5940437
    - name: GA_OKONOMI_STRENGT_FORTROLIG
      value: 9d135c69-105c-4364-86f4-e22916758e93

    # Attestasjon
    - name: GA_SOKOS_MF_ATTESTASJON_NASJONALT_READ
      value: ae748b4f-90d8-4635-afb6-60c24122a640
    - name: GA_SOKOS_MF_ATTESTASJON_NASJONALT_WRITE
      value: c641ea06-9d84-4320-9f77-4df2ab8042c3
    - name: GA_SOKOS_MF_ATTESTASJON_NOP_READ
      value: 5785b537-7a62-4c81-bb09-27e42e8146cd
    - name: GA_SOKOS_MF_ATTESTASJON_NOP_WRITE
      value: c67369c0-9918-4f31-a952-121fc9d6d9e3
    - name: GA_SOKOS_MF_ATTESTASJON_NOS_READ
      value: c8b782d6-12fd-4e1b-abed-04c6b09ad4e8
    - name: GA_SOKOS_MF_ATTESTASJON_NOS_WRITE
      value: b02c819d-91e5-4cac-baf5-3d2411869adf

    # Oppdragsinfo
    - name: GA_SOKOS_MF_OPPDRAGSINFO_NASJONALT_READ
      value: 992a8b83-5422-4cbf-af90-2d15fa0cfd88
    - name: GA_SOKOS_MF_OPPDRAGSINFO_NOP_READ
      value: a6fb82bd-cbca-4577-9156-fcabeb32404a
    - name: GA_SOKOS_MF_OPPDRAGSINFO_NOS_READ
      value: fae560aa-11da-4fcc-b794-508908ab9ed4

    # ZOS-Connect
    - name: ZOS_URL
      value: "https://155.55.1.82:9080/osattestasjonapi"