#!/bin/bash
echo "*********************************************************"
echo      "Running git pre-commit hook. Running Ktlint... "
echo "*********************************************************"
echo ""

# Gather the staged files - to make sure changes are saved only for these files.
stagedFiles=$(git diff --staged --name-only)

# Run ktlintCheck
./gradlew ktlintCheck

ktlintCheckStatus=$?

if [ "$ktlintCheckStatus" = 0 ] ; then
    echo ""
    echo "*********************************************************"
    echo "       ********************************************      "
    echo "              Ktlint - no violations found"
    echo "       ********************************************      "
    echo "*********************************************************"
    echo ""

    # Add staged file changes to git
    for file in $stagedFiles; do
      if test -f "$file"; then
        git add $file
      fi
    done
    #Exit
    exit 0
else
    echo ""
    echo "*********************************************************"
    echo "       ********************************************      "
    echo                  "Ktlint - found violations"
    echo              "Running ktlintFormat to fix issues..."
    echo "       ********************************************      "
    echo "*********************************************************"
    echo ""

    # Run ktlintFormat
    ./gradlew ktlintFormat

    # Run ktlintCheck again to verify if issues are fixed
    ./gradlew ktlintCheck

    ktlintCheckStatus=$?

    if [ "$ktlintCheckStatus" = 0 ] ; then
        echo ""
        echo "*********************************************************"
        echo "       ********************************************      "
        echo                    "Ktlint - issues fixed"
        echo "       ********************************************      "
        echo "*********************************************************"
        echo ""

        # Add staged file changes to git
        for file in $stagedFiles; do
          if test -f "$file"; then
            git add $file
          fi
        done
        #Exit
        exit 0
    else
        echo ""
        echo "*********************************************************"
        echo "       ********************************************      "
        echo        "Ktlint - found violations it could not fix."
        echo        "Fix the issues before trying to commit again."
        echo "       ********************************************      "
        echo "*********************************************************"
        echo ""

        #Exit
        exit 1
    fi
fi