name: Deploy application manual to dev

on:
  workflow_dispatch:

env:
  TZ: Europe/Oslo

permissions:
  contents: "write"
  id-token: "write"

jobs:
  build:
    name: Build/test & push image
    uses: navikt/moby-gha-workflows/.github/workflows/gradle-build-push-image.yaml@main
    secrets: inherit
    with:
      image-tag: snapshot

  deploy-dev:
    needs: build
    name: Deploy to dev-fss
    uses: navikt/moby-gha-workflows/.github/workflows/nais-app-deploy.yaml@main
    with:
      cluster: dev-fss
      resource: .nais/naiserator-dev.yaml
      image: ${{ needs.build.outputs.image }}