name: Reviewdog
on: [push]

jobs:
  code-style-violations:
    name: Check coding style violations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          ktlint_version: 1.0.1