name: Security

on:
  workflow_run:
    workflows: [ "Deploy" ]
    types:
      - completed
  schedule:
    - cron: '0 6 * * *'

env:
  LATEST_IMAGE: ${{ github.event.repository.name }}:latest

jobs:
  vulnerability-analyze:
    permissions:
      contents: "read"
      id-token: "write"
      security-events: write
    name: Security analyze
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      - uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

      - name: Login to Google Artifact Registry
        uses: nais/login@v0
        id: login
        with:
          team: okonomi
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

      - name: Run Trivy vulnerability scanner on docker image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ steps.login.outputs.registry }}/${{ env.LATEST_IMAGE }}
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'