name: Security

on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

permissions:
  contents: "read"
  id-token: "write"
  security-events: write

jobs:
  security-analyze:
    name: Security analyze
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    uses: navikt/moby-gha-workflows/.github/workflows/security.yaml@main
    secrets: inherit
    with:
      language: 'java-kotlin'